AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - jev-feels.gemspec

Metrics/MethodLength:
  Max: 30

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/feels.rb
    - lib/feels/string.rb
    - lib/jev-feels.rb
    - lib/jev-feels/string.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
