AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - jev-feels.gemspec

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Exclude:
    - lib/jev.rb
    - lib/jev/definition.rb
    - lib/jev/harness.rb

Metrics/ModuleLength:
  Exclude:
    - lib/jev.rb
    - lib/jev/definition.rb

Naming/PredicateMethod:
  Exclude:
    - lib/jev/result.rb

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/feels.rb
    - lib/feels/string.rb
    - lib/feels/active_model.rb
    - lib/jev-feels.rb
    - lib/jev-feels/string.rb
    - lib/jev-feels/active_model.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
